flex:
  version: 0.5.1
  workflows:
    setup-dependencies:
      command: pip install battenberg
    initialize-template:
      depends-on: setup-dependencies
      command: if ! [[ "$(git branch)" =~ "template" ]]; then battenberg install https://github.com/fp-mt-test-org/template-java-kotlin-library; fi
    build:
      command: ./gradlew build
    update-template:
      command: battenberg upgrade --no-input
service:
  name: '{{cookiecutter.component_id}}'
