flex:
  version: 0.5.1
  workflows:
    setup-dependencies:
      command: pip3 install battenberg
    build:
      command: ./gradlew build
    update-template:
      depends-on: setup-dependencies
      command: battenberg upgrade --no-input
service:
  name: '{{cookiecutter.component_id}}'
