name: DevX CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    env:
      flex: .devx-workflows/scripts/user/run-flex.sh

    steps:
    - name: Checkout Source
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup Dev Dependencies
      run: ./install-dev-dependencies.sh SETTING=VALUEEE

    - name: Initial Build & Unit Test
      run:  $flex build

    - name: Flex Build & Unit, Feature Test
      run: GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} auto_update=0 $flex build-test
